OCA/openupgradelib

openupgradelib/openupgrade.py, tests/test_openupgradelib.py
Fix some imports for old versions of OpenUpgrade.
=> [FIX] lib for working with old API (<= 7.0)

openupgradelib/openupgrade.py
Idea from @pedrobaeza https://github.com/OCA/OpenUpgrade/pull/370/#discussion_r40003024
=> [IMP] New function 'is_module_installed()'

openupgradelib/openupgrade.py
=> [FIX] use correct column name

openupgradelib/openupgrade.py
suggest usage in post-migration.
please merge, if true, please close, if not.
=> [IMP] docstrings `map_values`

openupgradelib/openupgrade.py
`True` as `old value` represents "is set", whereas `False` represets "is not set"
=> [IMP] (map_values): Support set & notset selectors

.travis.yml
Only when a tag is applied, the deployment will be done.
=> [IMP] .travis.yml: Add auto-deployment. Closes #24

openupgradelib/openupgrade.py
Reopening #27. Looking at the code, it seems like it gets quoted automatically.
=> Remove wrong docs

openupgradelib/openupgrade.py
which is <= 7.0. The problematic change was introduced by #30
=> [FIX] support OpenERP versions that don't have cr.savepoint

openupgradelib/openupgrade.py
this is used in https://github.com/OCA/OpenUpgrade/pull/576
=> [ADD] rename_property

openupgradelib/openupgrade.py, openupgradelib/openupgrade_tools.py
Needed for https://github.com/OCA/OpenUpgrade/pull/640
=> [RFR] Move column_exists so it can be used during loading

openupgradelib/openupgrade.py
Refactoring imports so that we can do without openerp.osv and friends when running in a 10.0 server. Tested with 7.0, 8.0, 9.0, 10.0.
=> [MIG] 10.0 imports

openupgradelib/openupgrade_90.py
Follow up of https://github.com/OCA/openupgradelib/pull/66/files#diff-65287faf97f9a32efd793c244fc9b0e4R10
=> [RFR] Local logger; don't force debug level

openupgradelib/openupgrade.py
* _columns doesn't exist on v10
* _sql_names dissapears also
* On >= 8.0, env is available for getting classes objects
=> [FIX] m2o_to_x2m: Compatible with Odoo v10

openupgradelib/openupgrade.py
=> [FIX] when renaming/deleting a module, rename/delete its xmlid

.travis.yml, tests/__init__.py
Fix https://github.com/OCA/openupgradelib/issues/76
=> [FIX] .travis.yml: Get python version without use env var

openupgradelib/openupgrade.py
Also set a method to deprecated.
=> [RFR] Python 3 compatibility

openupgradelib/openupgrade.py, tests/test_openupgradelib_with_openupgrade.py
This PR is to adapt `set_defaults` method to new api.
=> [FIX][set_defaults] New api adaptation

openupgradelib/openupgrade.py
This, in contrast of ``rename_columns``, performs all the steps for completely rename a field from one name to another. This is needed for making a complete renaming of a field with all their side features:
translations, filters, exports...
Call this method whenever you are not performing a pure SQL column renaming for other purposes (preserve a value for example).
This method performs also the SQL column renaming, so only one call is needed.
@Tecnativa
=> [ADD] rename_fields: New method for renaming completely fields

openupgradelib/openupgrade.py
Split by commits for better comprehension:
* Include mail.alias table
* Restrict update to matching records in existing replaces
* Include col_group_by key in the filters contexts.
@Tecnativa
=> [IMP] rename_fields: Several improvements

openupgradelib/openupgrade_90.py
Used in https://github.com/OCA/OpenUpgrade/pull/1203
=> [ADD] Replace account types in Odoo 9.0

openupgradelib/openupgrade.py
Avoid errors on migrated databases making a non-destructive disabling.
It analyzes all the existing active filters to check if they are still correct. If not, they are disabled for avoiding errors when clicking on them, or worse, if they are default filters when opening the model/action.
To be run at the base end-migration script for having a general scope. Only assured to work on >= v8.
When merged, I will make PRs for OpenUpgrade versions calling this method on end-migration/deferred step.
@Tecnativa
=> [ADD] disable_invalid_filters

openupgradelib/openupgrade.py
This method adds all the needed stuff for having a new field populated in the DB (SQL column, ir.model.fields entry, ir.model.data entry...).
It's intended for being run in pre-migration scripts for pre-populating fields that are going to be declared later in the module.
NOTE: This only works in >=v8 and is not needed in >=v12, as now Odoo always add the XML-ID entry:
https://github.com/odoo/odoo/blob/9201f92a4f29a53a014b462469f27b32dca8fc5a/odoo/addons/base/models/ir_model.py#L794-L802
:param: field_spec: List of tuples with the following expected elements for each tuple:
* field name
* model name
* SQL table name: Put `False` if the model is already loaded in the registry and thus the SQL table name can be obtained that way.
* field type: binary, boolean, char, date, datetime, float, …
=> [ADD] add_fields: Add a field definition

openupgradelib/openupgrade.py
Use case: You are renaming from model A to model B, and there are a many2one company dependent (property) field whose relation is model A. The field "value_reference" of these properties are of the form
'A,id'. We have to change them to 'B,id'.
@Tecnativa
=> [IMP] rename_models: Handle properties that reference to the old model

openupgradelib/openupgrade.py
=> [FIX] rename_models method

openupgradelib/openupgrade_90.py
Selecting all binary data at once will exceed memory limits, and get the
Odoo process killed.
Fetching one by one is not enough, since executing the SELECT to
retrieve all the table data can also fail with a Postgresql "out of
memory" error.
I had a bottleneck on res_partner.image, with almost 5k images to convert.
With this change this upgrade step was successful, and took around 6 minutes to run.
=> Fix conversion to attachment on large datasets

openupgradelib/openupgrade.py
=> Add missing space in SQL statement

setup.py
=> [FIX] Pypi license classifier, courtesy of Dmytro Katyukha

openupgradelib/openupgrade.py
Used in https://github.com/OCA/OpenUpgrade/pull/1531
=> [ADD] Chunked method

openupgradelib/openupgrade_merge_records.py
This PR fixes several things, some of them very important!
=> [FIX] openupgrade_merge_records

openupgradelib/openupgrade_merge_records.py
=> [FIX] merge_records: missing argument in _adjust_merged_values_orm

openupgradelib/openupgrade_merge_records.py
=> [FIX][DOC] _adjust_merged_values_orm: integer default case

openupgradelib/openupgrade_merge_records.py
=> [FIX] merge_records: _adjust_merged_values_orm

openupgradelib/openupgrade_merge_records.py
=> [FIX] Solve TypeError in _adjust_merged_values_orm

openupgradelib/openupgrade.py
=> [FIX] chunked: Adapt to all supported versions

openupgradelib/openupgrade.py
In v11, the `model_name` field of `ir_act_server` became stored.
=> [FIX] rename_models

openupgradelib/openupgrade.py
In v11, they introduced the mail activities.
=> [IMP] rename_models

.travis.yml, openupgradelib/openupgrade.py, openupgradelib/openupgrade_120.py
=> Support multilang updates in Bootstrap 3 to 4 migration

openupgradelib/openupgrade_120.py
=> [FIX+IMP] convert_string_bootstrap_3to4: Don't try to convert empty content + log faulty string

openupgradelib/openupgrade_merge_records.py
=> [FIX] merge_records: bad query in _change_foreign_key_refs

openupgradelib/openupgrade_merge_records.py
Related to https://github.com/OCA/openupgradelib/pull/157.
=> [FIX] merge_records: bad query in _change_foreign_key_refs (part 2)

requirements.txt
Avoid https://github.com/OCA/openupgradelib/issues/164.
=> [FIX] set lxml to version 4.3.4

openupgradelib/openupgrade.py
This method allows to copy data from some model's fields to other (or the same) model's equivalent fields, and transfers translated values.
@Tecnativa
=> [ADD] copy_fields_multilang method

openupgradelib/openupgrade_merge_records.py
Fixes _change_reference_refs_sql method.
=> [FIX] _change_reference_refs_sql

openupgradelib/openupgrade.py
=> [FIX] rename_models: Consider v12 ir.model.data for fields

openupgradelib/openupgrade.py
To be able to switch noupdate easily in several records.
=> [ADD] switch_noupdate

openupgradelib/openupgrade.py
This is how it works in modern Odoo versions.
@Tecnativa TT18838
=> [FIX] savepoint must raise

openupgradelib/openupgrade.py
All DB schemas from Odoo 7 to 9 define `workflow.triggers` with foreign keys without index.
The result is that executing this method is exponentially slow. Just a few hundred lines is already slow; try with some thousands and die waiting.
So, instead, now we create an index before performing the deletion, and then drop it after.
Note: before you ask, yes, I already tried deleting related items first and it doesn't help. :wink:
@Tecnativa TT18838 https://github.com/OCA/OpenUpgrade/pull/2068
=> Speed up workflow deletion

openupgradelib/openupgrade_80.py
Before this patch, the chosen `table` was inspected row by row, with a subselect that was also executed row by row to find messages attached to that model.
With this patch, all messages' max dates related with the used table are searched just once, and then joined with the target `table` to find records to update.
The result is reducing complexity from exponential to plain. In a sample database, one execution took from more than 1:30h to less than 1s.
@Tecnativa TT18838
=> [IMP] Speed up set_message_last_post

openupgradelib/openupgrade_80.py
Oops, this wasn't being logged!
@Tecnativa TT18838
=> [IMP] set_message_last_post: Log query

openupgradelib/openupgrade.py
This way it's easier to detect specially slow queries.
=> [IMP] logged_query: Log query execution time

openupgradelib/openupgrade.py
Workaround for https://github.com/OCA/openupgradelib/issues/172
=> [FIX] workaround for faulty index renames

openupgradelib/openupgrade.py
Helper to delete all foreign keys in a table automatically. Recommended to be executed in tables that are not going to be used anymore, but still you don't want to delete them.
@Tecnativa TT18838
=> [ADD] remove_table_fks: New method

openupgradelib/openupgrade.py
This PR adds a new tool method to move data from a given field to a given company_dependet field, both from the same table. Useful in cases when from one version to another one, some field becomes a 'company dependent' field.
Cc @Tecnativa TT21084
=> [ADD] new tool method to move data to a company dependent field

openupgradelib/openupgrade_merge_records.py
If you have a model inheriting from mail.thread with followers, there's a chance that merged records contain the same followers, leading to an unique constraint error.
This commit handles this, detecting these duplicates before it happens, and removing extra remaining records.
@Tecnativa TT22543
=> [FIX] merge_records: Handle duplicates in mail.followers

openupgradelib/openupgrade.py
In those versions, [there is a required column called `select_level`][1] whose [default value is `"0"`][2].
I'm adding it to `add_fields()` so it doesn't crash when trying to use it in those versions.
The crash looks like this:
```
2020-03-12 03:48:38,493 1 ERROR prod openerp.sql_db: bad query:
INSERT INTO ir_model_fields (
model_id, model, name, field_description, ttype, state
) VALUES (
117, 'product.template', 'pack', 'OU', 'bool', 'base'
) RETURNING id
Traceback (most recent call last):
File "/opt/odoo/custom/src/odoo/openerp/sql_db.py", line 247, in execute
res = self._obj.execute(query, params)
IntegrityError: null value in column "select_level" violates not-null constraint
DETAIL:  Failing row contains (9885, product.template, 117, pack, null, null, OU, bool, base, null, f, null, …
```
=> [FIX] let add_fields() work for Odoo <= v8

openupgradelib/openupgrade.py
For example, [in OpenUpgrade v9, the table `crm_case_section` is renamed to `crm_team`][1], but after that migration, the `crm_team` table still has these indexes and constraints (obtained from psql with `\d crm_team`):
```
Indexes:
"crm_case_section_pkey" PRIMARY KEY, btree (id)
"crm_case_section_code_uniq" UNIQUE CONSTRAINT, btree (openupgrade_legacy_10_0_code)
"crm_team_code_uniq" UNIQUE CONSTRAINT, btree (openupgrade_legacy_10_0_code)
"crm_team_message_main_attachment_id_index" btree (message_main_attachment_id)
Foreign-key constraints:
"crm_case_section_alias_id_fkey" FOREIGN KEY (alias_id) REFERENCES mail_alias(id) ON DELETE RESTRICT
"crm_case_section_create_uid_fkey" FOREIGN KEY (create_uid) REFERENCES res_users(id) ON DELETE SET NULL
"crm_case_section_parent_id_fkey" FOREIGN KEY …
```
=> [FIX] rename constraints and indexes when renaming table

openupgradelib/openupgrade_merge_records.py
Fixes https://github.com/OCA/OpenUpgrade/issues/1445
=> [IMP][merge_records] Improve ORM performance by using IN instead of ORs

openupgradelib/openupgrade.py
Detected as useful in OU v13 account.
cc @Tecnativa
=> [IMP] add_fields: Allow to set an initialization value

openupgradelib/openupgrade.py
Reverts OCA/openupgradelib#207
=> Revert "[FIX] rename_fields: Don't rename only by name + reverse order"

openupgradelib/openupgrade.py
=> [IMP] rename_models: Rename model reference in export profiles

openupgradelib/openupgrade_merge_records.py
Strange we didn't see this before.
=> [FIX] _delete_records_sql was deleting wrong ids

openupgradelib/openupgrade.py
In Odoo v12+, with `website` installed, and with its COW system for view edits, when a user clicks enables or disables a view marked as `customize_show=True` by using the dropdown in the website editor, Odoo creates a COW website-specific view which is enabled or disabled as desired.
When updating, COW views are usually not updated. If they contain any logic, it can lead to template rendering problems easily.
These errors make sense on some circumstances, but if it was just because the user used the customize show feature, they are disturbing and meaningless. With these methods provided here, this problem can be reduced to only meaninful occurrences.
The 1s method will compare website-specific views with their agnostic counterparts. If bodies are equal, they will be marked.
The 2nd method …
=> Add functions to autoupdate unmodified COW views

openupgradelib/openupgrade.py
When trying to use the `add_xmlid` function in a 14.0 repo it returned the following error:
Traceback error:
```
File "/opt/odoo/src/repo/addons/x_module/hooks.py", line 17, in pre_init_hook
openupgrade.add_xmlid(
File "/opt/odoo/data/.cache/pypi/openupgradelib/openupgrade.py", line 985, in add_xmlid
logged_query(
File "/opt/odoo/data/.cache/pypi/openupgradelib/openupgrade.py", line 1310, in logged_query
cr.execute(query, args)
File "<decorator-gen-3>", line 2, in execute
File "/opt/odoo/src/odoo/odoo/sql_db.py", line 101, in check
return f(self, *args, **kwargs)
File "/opt/odoo/src/odoo/odoo/sql_db.py", line 298, in execute
res = self._obj.execute(query, params)
Exception
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File …
```
=> [FIX] add_xmlid: 14.0 compatibility

openupgradelib/openupgrade.py
Problem detected in https://github.com/OCA/openupgradelib/pull/220#discussion_r560917035
@Tecnativa TT23136
=> [FIX] add FROM

openupgradelib/openupgrade.py
@Tecnativa TT23136
This should fix https://github.com/OCA/OpenUpgrade/pull/2299/checks?check_run_id=1740902592 from https://github.com/OCA/OpenUpgrade/pull/2299
=> [FIX] wrong operator

openupgradelib/openupgrade_merge_records.py
=> [FIX] merge_records: complete _change_translations_sql method

openupgradelib/openupgrade.py
Other modules may add the same field name in previous versions that you are now trying to add. We should warn about that, but not to fail.
@Tecnativa TT27288
=> [IMP] add_fields: Be tolerant to existing fields

openupgradelib/openupgrade.py
There are errors with the migrate decorator in Odoo 13.0 and possibly other releases, because the migration
scripts do not have a migrate attribute. This commit recifies that situation.
=> [FIX] Decorated functions should keep name and docstring.

openupgradelib/openupgrade.py
Detected in https://github.com/OCA/OpenUpgrade/pull/2761.
=> [FIX] date_to_datetime_tz: not using user_field_name in query

openupgradelib/openupgrade_merge_records.py
Regression of https://github.com/OCA/openupgradelib/pull/198
=> [FIX] Missing filter by model when merging mail.followers using SQL

.travis.yml
=> [FIX] travis: python libraries

openupgradelib/openupgrade_merge_records.py
If you have following situation:
- Target record with no followers.
- Record to merge 1 with follower 1.
- Record to merge 2 with follower 1.
When executing the merge and changing followers references, you get the following error:
```
IntegrityError: duplicate key value violates unique constraint "mail_followers_mail_followers_res_partner_res_model_id_uniq"
DETAIL:  Key (res_model, res_id, partner_id)=(..., ..., 1) already exists
```
And it's because both followers are changed to the target record. For avoiding this problem, we serialize the changes, so that for the second record to merge, no update is performed.
@Tecnativa
=> [FIX] _change_generic: Avoid error when changing mail.followers

openupgradelib/openupgrade_merge_records.py
=> [IMP] _adjust_merged_values_orm: add first_not_null option for chars

openupgradelib/openupgrade.py, openupgradelib/openupgrade_merge_records.py
=> [IMP] *: adapt to Many2manyReference fields

openupgradelib/openupgrade_merge_records.py
=> [FIX] merge_records: error in 'first_not_null' option

openupgradelib/openupgrade_merge_records.py
Firstly I thought on using new 'first_not_null' option in chars for its model_field, but later I understood that both fields are linked and thus I used the actual approach.
It's a bit corner case, and few models have many2one_reference for now, but maybe they increase in the future.
In v14, they are used in `ir.model.data`, `ir.attachment` and several mail models.
=> [IMP] merge_records: add 'merge' option for many2one_reference

openupgradelib/openupgrade_merge_records.py
In v14, models with Reference fields are:
ir.server.object.lines
ir.ui.menu
rating.rating
theme.ir.ui.view
=> [IMP] merge_records: add 'merge' option for Reference fields

openupgradelib/openupgrade_merge_records.py, requirements.txt
=> [IMP] merge_records: be able to adjust values by sql

openupgradelib/openupgrade_merge_records.py
=> [FIX] merge_records: oversight of _adjust_merged_values_sql improvement

openupgradelib/openupgrade_merge_records.py
=> [FIX] merge_records: oversight of apply_operations_by_field_type improvement

openupgradelib/openupgrade_merge_records.py
=> [FIX] _adjust_merged_values_sql: error in query parameter order

openupgradelib/openupgrade_merge_records.py
Oversight of the query formats.
Fast-track.
=> [FIX] _adjust_merged_values_sql: error in query format (avoid SQL)

openupgradelib/openupgrade_merge_records.py
=> [FIX] _adjust_merged_values_sql: error in unpacking values

openupgradelib/openupgrade_merge_records.py
Hope it's last oversight.
Fast-track.
=> [FIX] _adjust_merged_values_sql: error in transposing list

openupgradelib/openupgrade.py
The original idea of this function was to force the removal of noupdate=1 records when they disappear in a new version, as they are not removed regularly by Odoo update machinery.
But there's a hole in the data removal when the record is noupdate=0, as they are removed through the update process... if they can be removed. Maybe such records has been used somewhere, and they can't be removed due to restrict foreign keys, provoking a crash.
Using this method for trying to remove them on advance (before the Odoo update cleanup process), and marking them as noupdate=1 if not possible, provides a safest path for not having to deal with errors when performing such regular update. As this is totally opt-in, migration scripts developers can think if calling this method with such kind of records …
=> [IMP] delete_records_safely_by_xml_id: Mark as noupdate failed ones

openupgradelib/openupgrade_merge_records.py
When we already have recursive hierarchy, doing a merge of a parent into one of their children let the awkward situation where the child points to itself, so we avoid it checking this condition.
Same as done in https://github.com/OCA/OpenUpgrade/pull/2730.
=> [FIX] rename_xmlids: don't merge if hierarchy exists

openupgradelib/openupgrade.py
=> [IMP] delete_records_safely_by_xml_id: use WarningError and ValidationError

openupgradelib/openupgrade.py
=> [FIX] rename_models: bug in mail template query

openupgradelib/openupgrade.py
Based on https://github.com/OCA/OpenUpgrade/pull/3173.
=> [ADD] merge_models method

openupgradelib/openupgrade.py
=> [FIX] merge_models: minor fix in merge_models method

openupgradelib/openupgrade.py
=> [FIX] update_module_moved_models: minor fix in a query

openupgradelib/openupgrade.py
:'(
The field "module" in an integer instead of char.
=> [FIX] update_module_moved_models: fix queries

openupgradelib/openupgrade.py
- I Just want to show more detail about warning
=> [IMP] disable_invalid_filter: show more detail warning

openupgradelib/openupgrade.py, openupgradelib/openupgrade_90.py
=> [FIX] flake8

openupgradelib/openupgrade.py
- ``ir_translation`` table doesn't exist anymore in V16.
- a lot of openupgradelib function base queries on that table.
adding some ``if`` in the code.
=> [FIX] adapt common openupgradelib functions to V16. (ir_translation table has been removed)

openupgradelib/openupgrade_120.py
=> [FIX] convert_field_bootstrap_3to4 docstring

openupgradelib/openupgrade.py, openupgradelib/openupgrade_merge_records.py
=> [IMP] openupgradelib: don't break strings (code cleanup due to black)

openupgradelib/openupgrade.py
=> [FIX] add_fields: adapt to Odoo v16

openupgradelib/openupgrade.py, openupgradelib/openupgrade_merge_records.py
Extracted from https://github.com/OCA/OpenUpgrade/blob/16.0/openupgrade_scripts/scripts/base/16.0.1.3/pre-migration.py#L65C9-L65C64, in order to all versions get the benefit.
=> [ADD] get_model2table: method to map nonstandard table names

openupgradelib/openupgrade_merge_records.py
Fixes https://github.com/OCA/openupgradelib/issues/339
=> [FIX] merge_records: assure don't break on method="orm" if KeyError on model

openupgradelib/openupgrade.py
Avoid convertion of values which aren't set saving a handfull of useless queries.
TT46020 cc @Tecnativa 
please check @pedrobaeza
=> [IMP] convert_field_to_html: pre-clean empty values

openupgradelib/openupgrade.py
@pedrobaeza @MiquelRForgeFlow @hbrunn @legalsylvain
=> [IMP] copy_columns: Only copy not null values

openupgradelib/openupgrade_merge_records.py
Sometimes it might be needed to keep the data from the origin record instad of the target one.
A use case might be this one
https://github.com/OCA/product-variant/pull/373 where we are assigning the significant record to a brand new one which data isn't important at that moment.
cc @Tecnativa TT55092
ping @pedrobaeza 
fyi @lmignon 
Pending:
=> [IMP] merge_record: keep data from origin

.gitignore
It's annoying to be deleting it every time :sweat_smile:
=> [IMP] ignore vscode folder

openupgradelib/openupgrade_merge_records.py
In some case we might be intereseted in delete the origin records before updating the target with the gathered values to avoid some possible constraints like unique key values.
For example, when updating product_product barcode with a field specification of first_from_origin, the merge will fail as barcode is a unique key for that table.
To change this behavior, a new key `openupgradelib_delete_before_update` can be added to the field_spec dict.
cc @Tecnativa TT55184
please check @pedrobaeza
=> [IMP] merge_records: delete before update

openupgradelib/openupgrade.py
cc @Tecnativa 
fyi @victoralmau
=> [FIX] convert_field_to_html: don't consider NULL values

openupgradelib/openupgrade_160.py
In some cases, there's no analytic tags field, and you only want to convert the previous analytic account field to analytic distribution. As we can reuse the same method for that, let's do it.
=> [IMP] fill_analytic_distribution: Make tags optional

openupgradelib/openupgrade.py
Enable rename_xmlids method to change module translations (below v16).
Handles https://github.com/OCA/OpenUpgrade/pull/3882.
=> [ADD] update_module_moved_translations

openupgradelib/openupgrade.py
=> [IMP] rename_fields: rename ir_property names

openupgradelib/openupgrade.py, openupgradelib/openupgrade_merge_records.py
See https://github.com/odoo/odoo/commit/87307a9010c6c872fe6c746d5ece378ad90d038f.
=> [IMP] get_field2column_type, merge_records: support for properties fields 

openupgradelib/openupgrade.py
See https://github.com/odoo/odoo/commit/685cb96ec218601deb214d8ebe97dda008762d23.
=> [FIX] convert_to_company_dependent: support for html fields
