OCA/openupgradelib

docs/conf.py

Allow [Google](http://sphinxcontrib-napoleon.readthedocs.org/en/latest/example_google.html)- or NymPy-style docstrings by adding the napoleon preprocessor

[IMP] Google or NymPy docstrings

---

openupgradelib/openupgrade.py

Avoid rare (nasty) user errors, when a column name coincides with a SQL directive. e.g. `COLUMN` / `column`.

[IMP] docstrings `copy_columns`, `rename_columns`

---

openupgradelib/openupgrade.py

Although not a blocking point, as translations are re-loaded on module update, it's good for avoiding garbage records and preserve possible custom labels.

[IMP] update_module_names: Handle ir_translation

---

openupgradelib/openupgrade.py

Making the work to port @hbrunn's patch for the problem with inherited fields by delegation here to the lib. I'm going to check it right now also on a migration and let you know the result.

[FIX] set_defaults: Cope with inherited fields by delegation

---

openupgradelib/openupgrade.py

Closes https://github.com/OCA/OpenUpgrade/issues/373
@sebalix I'm afraid you should check if all used methods are totally compatible with these versions, as the used version for all of them has been 8.0, but with this patch you will be able to load OpenUpgrade 6.0 branch (and I have also checked 5.0).
cc @StefanRijnhart

[FIX] Compatibility for OpenERP versions prior to 6.1

---

openupgradelib/openupgrade.py

It allows the migrator to ignore some expected error codes from Postgres.

Add new context manager allow_pgcodes.

---

openupgradelib/openupgrade.py

Reopening #28. If a migration fails, it will get reverted.

Avoid broken updates

---

openupgradelib/openupgrade.py

this fixes warnings when building the openupgrade documentation:
```
/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py:docstring of openupgradelib.openupgrade.copy_columns:4: WARNING: Field list ends without a blank line; unexpected unindent.
/var/tmp/openupgrade/openupgradelib/openupgradelib/openupgrade.py:docstring of openupgradelib.openupgrade.map_values:9: WARNING: Field list ends without a blank line; unexpected unindent.
```

[FIX] docstring warnings

---

openupgradelib/openupgrade.py

rename_models() does not change 'module' field in ir_model_fields.
This PR adds 'module' query to properly rename model fields.
A separate query is used from the one that updates 'relation' field as it's not always the same.

Update module field in ir_model_fields when calling rename_models.

---

openupgradelib/openupgrade.py

a nice side effect of this is that we can say `openupgrade.AsIs` when this is merged

[ADD] lift_constraints

---

openupgradelib/openupgrade.py

Decorator talks about pass_env, but actual argument is use_env.

[FIX] Fix argument name in migrate __doc__ to actual argument.

---

setup.py

Installing a library must not fix requirements versions, unless strictly necessary
In this case, the problem is that installing openupgradelib would
downgrade the wheel package, which is undesirable.

[FIX] installing a library must not fix requirements versions

---

openupgradelib/openupgrade.py

With these minimal changes, we allow to reallocate all the resources related to a module that has been merged into others in later versions. For example, email_template in version 8 that has been integrated in mail module in version 9.

[IMP] update_module_names: Add merge option

---

openupgradelib/openupgrade_90.py

This method converts the 8.0 binary fields to attachments like Odoo 9.0 makes with the new attachment=True attribute. It has to be called on post-migration script, as there's a call to get the res_name of the target model, which is not yet loaded on pre-migration.
You need to rename the involved column in pre-migration script if you don't want to lose your data in the process.
This method also removes after the conversion the source column for avoiding data duplication.
This is done through Odoo ORM, because there's a lot of logic associated with guessing MIME type, format and length, file saving in store... that is doesn't worth to recreate it via SQL as there's not too much
performance problem.
:param env: Odoo environment
:param field_spec: A dictionary with the ORM model name as key, …

[ADD] convert_binary_field_to_attachment

---

openupgradelib/openupgrade.py

Also changed the argument selection to an if-else statement because the environment actually evaluates falsy in the base modules pre migration script because the environment does not yet contain any models.

[FIX] Adapt code to docstring by passing env by default starting from 10.0

---

openupgradelib/openupgrade_80.py

this is necessary to make the automated build of the documentation work, as it pulls all of openupgradelib to generate docs, see also https://github.com/OCA/OpenUpgrade/pull/794

[ADD] protect openerp imports

---

openupgradelib/openupgrade.py

mind you that python doesn't have lazy evaluation of function parameters, so also the fallback we pass to `getattr` is evaluated immediately

[FIX] support versions without _fields

---

openupgradelib/openupgrade.py
requirements.txt

this is meant to allow loading `noupdate="1"` records and being sure nothing bad happens when doing this.
Currently, if you `load_data` with records that were noupdate, forcecreate=False and deleted, odoo will generate a `create`, which fails if there are any required fields that are not included in the xml
cc @pedrobaeza

[ADD] support update mode where we never try to create records

---

openupgradelib/openupgrade.py

str() should never be used in Python 2 if you can not know the encoding
of the string.
In this case it can log and raise a UnicodeEncodeError in migration.log
instead of the exception causing the error, and you cannot know why
your migration failed.
I use repr() for Python 2. It's not perfect but the exception is
displayed and the stacktrace is in the log because of logger.exception(),
which is bypassed if str() cause another exception.
Resolve #90

Fix logging with non-ascii characters in exception.

---

openupgradelib/openupgrade.py
openupgradelib/openupgrade_merge_records.py

New method for merging several records into a target one
NOTE: This should be executed in end migration scripts for assuring that
all the possible relations are loaded and changed. Tested on v11.
:param env: Environment variable
:param model_name: Name of the model of the records to merge
:param record_ids: List of IDS of records that are going to be merged.
:param target_record_id: ID of the record where the rest records are going
to be merge in.
:param field_spec: Dictionary with field names as keys and forced operation
to perform as values. If a field is not present here, default operation
will be performed.
Possible operations by field types:
* Char, Text and Html fields:
- 'merge' (default): content is concatenated with an ' | ' as separator
- other value: content on target record is …

[ADD] merge_records: New method for merging several records into a target one

---

openupgradelib/openupgrade.py

This removes in the safest possible way the records whose XML-IDs are passed as argument.
:param xml_ids: List of XML-ID string identifiers of the records to remove.

[ADD] delete_records_safely_by_xml_id

---

openupgradelib/openupgrade_80.py

More an FYI than a PR.
I was having big delays in large tables running set_last_message_post, in fact I never had it complete even in a couple of hours before I just couldn't be bothered.  
So I rewrote in SQL.  On a table with a couple of million invoices completes in ~7 minutes (that is the whole migration, pre, install and post).  This specific query isn't logged but at a guess takes around 5. 
That said, I am yet to verify its correctness but a cursory check looks very good.

Performance - SQL version of last_message_post

---

openupgradelib/openupgrade_merge_records.py

`record_ids` before was a `list` and now is a `tuple`.

[FIX] merge_records: tuples and lists don't sum

---

openupgradelib/openupgrade_merge_records.py

If you see in the code, the merges in the `char` case are different from `text` and `html` case.

[FIX][DOC] _adjust_merged_values_orm: char default case

---

openupgradelib/openupgrade_merge_records.py

Fixes https://github.com/OCA/openupgradelib/issues/125.
By default, the `search` method avoids the inactive records.

[FIX] merge_records (orm): take into account inactive records

---

openupgradelib/openupgrade_merge_records.py

3 things:
* **[FIX] Handle better translatable fields**
When merging records from a model that has translatable fields, before this patch, the translations for all the records are reassigned to the target record, provoking duplicated translations. This is even forgiven in v12.
With this new approach, target translation has priority, and if not present, then the first found is assigned instead.
* **[IMP] merge_records: Put exception condition on records to be merged**
For avoiding that the target record is also included in records to be merged.
* **[IMP] Check which records to be merged exist**
This way, if you pass unexisting records to the method, it won't crash.
In addition, if no records to be merged after this purge, then just return w/o error.
Fixes #13 
@Tecnativa

merge_records: translations + exception

---

openupgradelib/openupgrade_merge_records.py

Merge records on SQL mode didn't take into consideration relational tables where is no id column_name.
Will this break another scenario?
I'm not so sure.

[FIX] Merge records on sql rel tables

---

openupgradelib/openupgrade.py

Into `update_module_moved_fields` function, the SQL request to update `ir.model.data` for moved fields is incorrect.
We want to update metadata only for model `ir.model.fields`.
Without that, all metadata for `module` with `res_id` returned from `ir.model.fields` are updated.
_Example on my project, for model `res.partner` and field `fax`, we want to move the definition from module `base` to module `xxxxx_partner`:_
```
SELECT imf.model, imd.model, imf.name, imd.name, field_description
FROM ir_model_fields imf, ir_model_data imd
WHERE
imf.model = 'res.partner' AND
imf.name IN ('fax') AND
imd.module = 'base' AND
imd.res_id = imf.id AND
imd.id NOT IN (
SELECT id FROM ir_model_data WHERE module = 'xxxxx_partner'
);
```
_The request without my fix returns too many metadata:_
```
model    | …
```

[FIX] SQL request into moved_fields function

---

openupgradelib/openupgrade_merge_records.py

When try to merge two records of a model that have a text fields: one of records has a content but the other one is empty this error raised:
```python
TypeError: sequence item 0: expected str instance, bool found
```
The line `vals[field.name] = ' | '.join(l)` in openupgradelib._adjust_merged_values_orm() is trying to join something like `['text content', False]` and that generate the TypeError exception. Here is part of the code
```python
l = all_records.mapped(field.name)
if field.type in ('char', 'text', 'html'):
if not op:
op = 'other' if field.type == 'char' else 'merge'
if op == 'merge':
vals[field.name] = ' | '.join(l)
```
[source here](https://github.com/OCA/openupgradelib/blob/master/openupgradelib/openupgrade_merge_records.py#L331)
This can be reproduced by trying to merge two …

[FIX] openupgradelib: TyperError when trying to join and use min() function in bool with strings values

---

.travis.yml
openupgradelib/openupgrade.py
openupgradelib/openupgrade_120.py
openupgradelib/openupgrade_merge_records.py
openupgradelib/openupgrade_tools.py
requirements.txt
setup.py
tests/__init__.py
tests/test_openupgradelib.py

In `openupgrade_tools`, I added some methods to perform transformation of XML strings based on given specs. The specs support some HTML-specific features, such as classes and styles. I provide also a handy shortcut for spec declaration.
I also added `openupgrade_120` with the spec for the Bootstrap 3 to 4 migration and a simple method that leverages the framework and spec to convert an XML string.
@Tecnativa

[IMP] Add XML conversion framework and Bootstrap 3 to 4 converter

---

openupgradelib/openupgrade_120.py

Fix typo in openupgrade_120 in `_convert_field_bootstrap_3to4_orm` method. it have to call string conversion.

[FIX] typo in 12.0 tools

---

openupgradelib/openupgrade.py

We left the model mail.message.subtype :S

[IMP] rename_models: add mail_message_subtype in rename_models

---

openupgradelib/openupgrade_120.py
openupgradelib/openupgrade_tools.py

Without this patch, if an XML node had a `style="height:333px"` and the rules set it to `style="height:222px"`, there was no way to avoid that.
Now, if you *really* want to replace a style or attribute, then just add it to the list of styles/attributes to remove. Otherwise, it will only be added if it was missing before.
@Tecnativa

[IMP] Improvements to website migration

---

openupgradelib/openupgrade_tools.py

Trying to fix the "AttributeError: 'lxml.etree._Attrib' object has no attribute 'copy'".

[FIX] convert_xml_node: node.attrib doesn't have copy() method

---

openupgradelib/openupgrade_tools.py

`.attrib` is a dict-like proxy to the XML node attributes, but it lacks a `setdefault()` method.
Now this does the same, but without calling that method.
@Tecnativa

[FIX] Remove call to `setdefault()`

---

openupgradelib/openupgrade_merge_records.py

Using `merge_records` with v12 causes a ValueError: `External ID not
found in the system: base.field_ir_property_value_reference`.
Auto generated field's XML ID includes additional underscore symbol
between model and field names in Odoo v12, therefore adding a version
check to support v12 too.

[FIX] openupgrade_merge_records: field XML ID v12

---

openupgradelib/openupgrade.py

[IMP] For small tables it's perfectly acceptable to drop index and then let Odoo recreate it, but with large tables this scenario is rather costly.

[IMP] Renaming index instead of dropping it while renaming columns

---

openupgradelib/openupgrade.py

- Until now, `sql_type` was being ignored. Fix #171 and respect it.
- Use safe sql builder. If, i.e. one column was called "select", previous implementation with `AsIs()` would fail.
@Tecnativa

[FIX] add_fields: Respect sql_type and build safe query

---

openupgradelib/openupgrade.py

Reuse the `ustr()` tool that Odoo provides, also making it more similar to how this is supported upstream in v11+ since https://github.com/odoo/odoo/pull/35834.
Fix #180.
@Tecnativa

[FIX] Unify the way to convert query to unicode

---

openupgradelib/openupgrade.py

Cause: https://github.com/odoo/odoo/commit/7c47eb185443af08a55b0045c6a78f74151dc083.

[FIX] Avoid deprecated openerp warning in >= 13.0

---

openupgradelib/openupgrade.py

Following #184, here I'm adding more indexes to speed up workflow deletion even more. Let's save even more hours.
This time, I'm also adding `drop_indexes=False` argument. The created index names matches those created/deleted by Odoo addon update. This way, if you leave indexes there, subsequent calls will be even faster, and a simple addon update will let Odoo find and remove them.
@Tecnativa TT18838 https://github.com/OCA/OpenUpgrade/pull/2068

[IMP] Faster workflow deletion

---

openupgradelib/openupgrade.py

It seems like reassigning variables here changes the contents of the `to_index` dict, resulting in weird errors. Regression introduced in #189.
Fixed by changing variable names to avoid reusing them.
<details><summary>Failure logs</summary>
```
2019-10-31 14:33:16,150 1 ERROR prod OpenUpgrade: procurement: error in migration script procurement/migrations/8.0.1.0/pre-migration.py: TypeError('SQL identifiers must be strings',)
2019-10-31 14:33:16,150 1 ERROR prod OpenUpgrade: SQL identifiers must be strings
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/openupgradelib/openupgrade.py", line 1691, in wrapped_function
if use_env2 else cr, version)
File "/opt/odoo/auto/addons/procurement/migrations/8.0.1.0/pre-migration.py", line 53, in migrate …
```

[FIX] delete_model_workflow: Do not reassign variables

---

openupgradelib/openupgrade.py

In case your users put the domain there instead of the context.
Prevents the migration breaking at the very end with
```
File "/home/ou9/parts/odoo/odoo/addons/base/migrations/10.0.1.3/end-migration.py", line 31, in migrate
openupgrade.disable_invalid_filters(env)
File "/home/ou10/openupgradelib/openupgradelib/openupgrade.py", line 2103, in disable_invalid_filters
if not context.get(key):
AttributeError: 'list' object has no attribute 'get'
```

[FIX] Invalidate filter if context is not a dict

---

openupgradelib/openupgrade.py

Rename references in user-defined filters (ir.filters) when renaming model.

[FIX] rename references in ir.filters when renaming models

---

openupgradelib/openupgrade_merge_records.py

Removing env.cr.savepoint that requires that base model is loaded in registry
@Tecnativa

merge_records: Allow to run it by SQL on base pre-migration

---

openupgradelib/openupgrade.py

Doing that, you can rename exports from other models that match the field name.
I don't know how can this be so many time there without being aware of the problem...
TT24303

[FIX] rename_fields: Don't rename only by name + reverse order

---

openupgradelib/openupgrade.py

If the field is Binary with attachment=True, the attachments are not renamed, and the content was lost.
Here we apply it unconditionally for every rename, as if the field is not binary or without attachments, the result of this will be 0 rows changed.
@Tecnativa TT23524

[FIX] rename_fields: Rename attachments for binary field

---

openupgradelib/openupgrade_merge_records.py

I think this fix is better and clearer than https://github.com/OCA/openupgradelib/pull/216.
Thus, if this one is merged, then https://github.com/OCA/openupgradelib/pull/216 should be closed.

[FIX] merge_records: assure columns exist in _change_generic

---

AUTHORS.rst
openupgradelib/openupgrade.py

Adapting `load_data` to search for the file to load in the --upgrade-path if it cannot be found in the module directory tree.

[ADD] Support for --upgrade-path

---

openupgradelib/openupgrade.py

As was implemented in the pre-migration script of 13.0/base: https://github.com/OCA/OpenUpgrade/blob/13.0/odoo/addons/base/migrations/13.0.1.3/pre-migration.py#L752

[RFR] Merge records in case of an existing module category in rename_xmlids

---

openupgradelib/openupgrade.py

Fixes 
```
odoo.sql_db: bad query: SELECT "purchase_report".id FROM "purchase_report" WHERE ("purchase_report"."state" != 'cancel') ORDER BY "purchase_report"."date_order" DESC,"purchase_report"."price_total" DESC  limit 1
OpenUpgrade: FILTER DISABLED: Global Filter 'Monthly Purchases' for model 'purchase.report' has been disabled as it contains an invalid domain.
odoo.sql_db: bad query: UPDATE "ir_filters" SET "active"=false,"write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (10)
OpenUpgrade: base: error in migration script base/migrations/10.0.1.3/end-migration.py: InFailedSqlTransaction('current transaction is aborted, commands ignored until end of transaction block\n',)
OpenUpgrade: current transaction is aborted, commands ignored until end of transaction block
```

[FIX] Test invalid filters using a cursor savepoint

---

openupgradelib/openupgrade.py

Fixes https://github.com/OCA/OpenUpgrade/pull/2299/checks?check_run_id=1741234705#step:12:7045 from https://github.com/OCA/OpenUpgrade/pull/2299.
You cannot use `IN` to search in an `ARRAY`, which is the type of data that psycopg2 passes to postgres from a python `list`. Also, an empty `tuple` would fail too. Using `= ANY (%s)` is the safest.
@Tecnativa TT23136

Replace IN for ANY

---

openupgradelib/openupgrade.py

The deletion of ir_model_fields is harmful as it drops ir.property by cascade. This is currently what happens with product settings in OpenUpgrade 9.0. I'm working on an actual fix, but it would be good to prevent this unnoticed destruction of data in the mean time.

[RVT] rename fields: revert deletion of existing ir_model_fields

---

openupgradelib/openupgrade.py

If not, inherited modules like `website_crm` or so won't benefit from this mechanism.
@Tecnativa TT19845

cow_templates_replicate_upstream: Run in end migration

---

openupgradelib/openupgrade.py

When bridging multiple versions during a migration, custom modules are
usually only available in the target version. If we run this method with
every version, filters that depend on fields from these modules will be
invalidated prematurely. Also, running the method to invalidate filters on
every version has a performance impact.
The target version can be provided with an environment variable
```
export OPENUPGRADE_TARGET_VERSION=13.0
```

[IMP] Defer invalidating filters

---

openupgradelib/openupgrade.py

Added that this module is not needed since v13 in update_module_moved_fields docstring

[UPD] update_module_moved_fields: unneeded since v13

---

openupgradelib/openupgrade_merge_records.py

Adding the new argument `extra_where`, we are able to change a FK reference depending on an extra condition, so not all ocurrences are replaced.
This is useful for example when we have a unique record for all companies, and on new version, there should be one record per company. We perform the split, and we need to replace references for only a specific company (extra_where="AND company_id = X").
Retro-compatibility is kept as the argument is optional, and a safeguard has been introduced for skipping models where the condition can't be fulfilled if the field doesn't exist (so we are not able to say if the reference should be replaced or not).
@Tecnativa TT28115

[IMP] _change_foreign_key_refs: Add extra_where params

---

openupgradelib/openupgrade_merge_records.py

This way we avoid calling getattr().

[FIX] _adjust_merged_values_orm: get target_record_id value first

---

openupgradelib/openupgrade.py

This way, we can detect cases where the method is called wrong, for example passing the cr instead of the env.

[IMP] delete_records_safely_by_xml_id: restrict Exception

---

openupgradelib/openupgrade_merge_records.py

psycopg2 converts lists to `ARRAY` when transposing params in the query, so we have to make sure that the iterable passed on our methods are tuples for a proper conversion.
@Tecnativa

[FIX] openupgrade_merge_records: Ensure a tuple is passed on SQL queries

---

openupgradelib/openupgrade_merge_records.py

This way, we can be safe when passing a field_spec, but the model is one that may have many other fields added in custom modules.

[IMP] merge_records: option to exclude all fields not in field_spec

---

openupgradelib/openupgrade_merge_records.py

Adding a new keyword argument allows us to pass a possible new model for using this function in other contexts like transferring the generic stuff from one model to another (e.g. from `account.invoice` to `account.move` in the v12 > v13 migration).
When adding this feature, I have discovered as well a bug in current code using the SQL method, where barely no followers where transferred, as the query was not having into account the model, so as soon as the partner is follower of any record of any model with such ID, then it's not transferred.
@Tecnativa

[FIX+IMP] _change_generic: Allow to transfer generic stuff between models + fix followers through SQL

---

openupgradelib/openupgrade.py

There are models, like `ir.rule`, where its records usually are `noupdate = True`, and they may affect the databases if they are left in the database.
For example, this issue happens in stock (v11) because there are two `ir.rule`, one in 'procurement' module and the other in 'stock' module, that both have the same xmlid name (product_pulled_flow_comp_rule), and in v11, procurement is merged in stock.

[IMP] update_module_names: set noupdate = FALSE in remaining occurrences

---

openupgradelib/openupgrade.py

Logger.warn() is deprecated in last python versions, and we should try to avoid filling logs with useless DeprecationWarning's.

[IMP] *: warn -> warning

---

openupgradelib/openupgrade.py

Until today it didn't matter (and still doesn't matter, but maybe in the future, who knows...) because the usual models in that column are product.template, product.category, res.partner, product.product, ...

[FIX] rename_models: also rename models in res_id of ir.property

---

openupgradelib/openupgrade.py

Odoo CE has support the list of upgrade paths, we should be support it to PATH_TO_openupgrade_scripts_MODULE of any repository does not need to contain source code

[IMP] upgrade_path: support upgrade paths (separated by commas)

---

openupgradelib/openupgrade.py

This new method renames the models in the reference fields.
Also fixes _change_reference_refs_sql method.

[IMP] rename_models: rename the models in the reference fields

---

openupgradelib/openupgrade.py

This error will save archive all filters
=> Prefer providing only the items necessary for your intended use as attributes of `odoo.tools.safe_eval`

[FIX] disable_invalid_filters: <module 'time' (built-in)> can not be used in evaluation contexts

---

openupgradelib/openupgrade.py

Reference:
https://github.com/odoo/odoo/blob/b35f127c86c1d271a76dae7186a96190e8558c73/odoo/api.py#L491

[IMP][15.0] openupgradelib: Since Odoo 15.0, Environment.manage() is useless

---

openupgradelib/openupgrade.py

[ADD] update_module_moved_models

---

openupgradelib/openupgrade.py

Ref: https://github.com/odoo/odoo/blob/15.0/odoo/addons/base/models/ir_filters.py#L39-L44

[FIX] disable_invalid_filters: datetime / context_today / relativedelta is not defined

---

openupgradelib/openupgrade.py

[ADD] delete_constraint_safely: method to delete constraints

---

openupgradelib/openupgrade.py

In v15, this method is used several times and some times in tables that usually have many rows.

[IMP] convert_field_to_html: be ablet to avoid spamming query for each row

---

openupgradelib/openupgrade.py

This brings the functionality to be able to also delete child records when using delete_records_safely_by_xml_id. 
The related issue / feature request is: https://github.com/OCA/openupgradelib/issues/278

[IMP] delete_records_safely_by_xml_id: Added functionality to also delete child records

---

openupgradelib/openupgrade_130.py

I'm using these functions in the migration script I'm going to create a pull request for l10n_nl for, but they should be useful for any localization module. Especially the `unlink_invalid_tax_tags_from_*` functions. When migrating the `account` module from 12 to 13, the tax tags are structured differently; they are assigned to account.tax.repartition.line instead of accoun.tax itself. However, the `account` module copies each tag to each new repartition line that it /could possibly/ belong to. This causes issues in the migrated instance in 13.0 and beyond.
I'm using these functions here: https://github.com/OCA/OpenUpgrade/pull/3184

[13.0][ADD] Add helper functions that make the migration of tax tags for localizations modules l10n_* a lot easier.

---

openupgradelib/openupgrade_130.py

I accidentally left a harcoded `l10n_nl` in a few queries: https://github.com/OCA/openupgradelib/blob/3184c8298913ff5f02a9700b5174baf0caf046ea/openupgradelib/openupgrade_130.py#L113
It is an embarrassing mistake I overlooked, but I fixed it by adding an extra function argument.
Please only merge this together with: https://github.com/OCA/OpenUpgrade/pull/3588
Otherwise, that will break.

[FIX] Fixed the 13.0 tax helper functions I added.

---

openupgradelib/openupgrade_70.py

Use the same relative import as in the other openupgrade_xx files.

[FIX] bad openupgrade import in legacy code for openupgrade 7.0

---

openupgradelib/openupgrade.py

Cc @Tecnativa TT41247
From Odoo version 15.0, in `mail.activity.type` model, the field that stores a reference to `res.model` is `res_model` and not `res_model_id` field as in previous versions, so we need to take this into account in the `merge_models` method when updating `mail.activity.type`.
Odoo 14.0: https://github.com/odoo/odoo/blob/fe87755a4499f68de4625fd9940f25960896bc55/addons/mail/models/mail_activity.py#L58
odoo 15.0: https://github.com/odoo/odoo/blob/5553ad50bf54bef986038f94e8c8462e2547a927/addons/mail/models/mail_activity_type.py#L46

[FIX] mail_activity_type rename in merge_models method

---

docsource/index.rst

Rational : 
- max depth was set to 2 in openupgradelib documentation : https://github.com/OCA/openupgradelib/blob/master/docsource/index.rst
- max depth is set to 3 in openupgrade documentation : https://github.com/OCA/OpenUpgrade/blob/documentation/docsource/index.rst
As a result, method signatures and explanation are not shown. ([ref](https://github.com/OCA/OpenUpgrade/pull/3863#issuecomment-1549799519))
This PR should fix the problem.

[FIX] toctree: set 3 maxdepth to see all the methods signatures

---

.github/workflows/documentation-commit.yml
.github/workflows/documentation.yml
DEVELOP.rst
README.rst

For the time being, CI is green, if there are warning during the call of sphinx to build documentation.
https://github.com/OCA/openupgradelib/actions/runs/4993898715/jobs/8943675293#step:7:28

[DOC] turn CI into red, if there are warning in sphinx call

---

openupgradelib/openupgrade_merge_records.py

I added Serialized fields support as they are very similar to 'Jsonb' fields and could be done in the same operation.

[IMP] merge_records: support Serialized and 'Jsonb' fields (adapt to Odoo v16)

---

openupgradelib/openupgrade.py

[FIX] delete_record_translations: adapt to Odoo v16

---

openupgradelib/openupgrade.py

I notice it going to error , check this PR `https://github.com/OCA/OpenUpgrade/pull/4040` 
Why not using `jsonb_build_object`

[FIX] delete_record_translation: invalid input syntax for type json

---

openupgradelib/openupgrade.py

fix filtering of columns in `delete_record_translations()` for versions >= 16. the loop was wrong as it was changing the size of the list while looping over it.

[FIX] fix columns filter in `delete_record_translations()` for versions >= 16

---

openupgradelib/openupgrade_merge_records.py

* Add "first not null" merging operation for the following field types : int,float,monetary,date,datetime,selection
* Replace deprecated `recompute` in version 16 to avoid warning at each merge

[IMP] openupgrade_merge_records: add first_not_null operation on several field types

---

openupgradelib/openupgrade.py

If not , rating feature will be gone for good

[IMP] rename_modules: rename rating mixin parent_res_model as well

---

openupgradelib/openupgrade.py

SEE [Issue](https://github.com/OCA/openupgradelib/issues/347)
@pedrobaeza I have added only the `column_exists` condition as it implicitly checks whether the table exists or not:

[FIX] `rating_rating` does not have `parent_res_model` column

---

openupgradelib/openupgrade_160.py
openupgradelib/openupgrade_tools.py

BS4 to BS5 transformation yeahhhhh

[IMP] openupgrade_160, openupgrade_tools: BS4 to BS5 transformation yeahhhhh

---

openupgradelib/openupgrade_160.py

Convert v15 analytic tags with distributions to v16 analytic distributions.
Extracted and adapted from Viindoo original queries in their migration scripts.
@Tecnativa

[ADD] openupgrade_160: fill_analytic_distribution

---

openupgradelib/openupgrade_tools.py

When the fragment has no common node, lxml wraps the code under a common one.
This content for instance:
```html
<p><p/><p></p>
```
is parsed as:
```html
<div><p><p/><p></p></div>
```
To avoid this we force a custom wrapper tag on every parsed string so every xml
receives the same treatment and we can extract it later with no harm.
We don't want to update any fragment which has no changes after all the
replacements are checked. For that cases we'll return the original string.
At the end, we just trim our initial custom wrapper tag and return our
treated string.
I made this test case and tested it in a v16 shell:
```python
from openupgradelib.openupgrade_160 import convert_string_bootstrap_4to5
html_string = "<div><p></p><p></p></div>"
html_string_parsed = …
```

[IMP] convert_html_fragment: prevent lxml wraps and false positives

---

openupgradelib/openupgrade_160.py

related: https://github.com/OCA/OpenUpgrade/pull/4205#issuecomment-1790261528
```python
>>> ids = [1, 3, 5]
>>> (ids,)
([1, 3, 5],)
>>> (tuple(ids),)
((1, 3, 5),)
```
cc @Tecnativa TT45734
ping @pedrobaeza

[FIX] openupgrade_160: _convert_field_bootstrap_4to5_sql ids

---

openupgradelib/openupgrade_tools.py

If the HTML string to convert is a fully XML compliant file including the header `<?xml version="...?>`, the wrapping process is breaking the final result, as the expected XML syntax doesn't include `?` in the middle and lxml returns a weird result `<?xml version="...??>` with 2 interrogations.
With this commit, we are not wrapping if we detect the XML header.
Fine-tune of #349 
@Tecnativa

[FIX] convert_html_fragment: Don't wrap full XMLs

---

openupgradelib/openupgrade_160.py

Fixes https://github.com/OCA/openupgradelib/pull/338#discussion_r1390249774
- Fix update query
- Avoid templating the sql directly from the method parameters.
ping @lijoantony

[FIX] _convert_field_bootstrap_4to5_sql: convert parameters

---

openupgradelib/openupgrade.py

The deprecated warning was removed on 17 (https://github.com/odoo/odoo/commit/d200dcfb2c912353d404312b9d9484846868cf96)

[FIX] core.exceptions.UserError --> Warning

---

openupgradelib/openupgrade_160.py

according to the [docs](https://www.psycopg.org/docs/extras.html#json-adaptation), we can rely on those values to be dicts.
Fixes https://github.com/OCA/OpenUpgrade/issues/4263

[FIX] _convert_field_bootstrap_4to5_sql: Detect json and convert its values

---

openupgradelib/openupgrade_160.py

When trying to use fill_analytic_distribution for migrating purchase module (https://github.com/OCA/OpenUpgrade/pull/4303), I got the following error :
`column line.analytic_account_id does not exist`
The problem here is that the column is named account_analytic_id...
I then added a named parameter to fill_analytic_distribution() function to be able to set the column name holding analytic account id as done for the other columns related to analytic distribution

[FIX] fill_analytic_distribution get analytic account column

---

openupgradelib/openupgrade.py

clean_transient_models
-------
Clean transient models to prevent possible issues due to chained data.
To be run at the base post-migration script for having a general scope.Only works on > v8.
Used in https://github.com/OCA/OpenUpgrade/pull/4374.

[ADD] clean_transient_models

---

openupgradelib/openupgrade.py
openupgradelib/openupgrade_tools.py

Fixes:
- https://github.com/OCA/openupgradelib/issues/362

[FIX] chunked: explicitly flush on every iteration

---

openupgradelib/openupgrade_tools.py

Fixes https://github.com/OCA/openupgradelib/pull/364.

[FIX] invalidate_cache: avoid f-string in warning

---

openupgradelib/openupgrade.py

changed on 17.0
(https://github.com/odoo/odoo/commit/5bf1207c8cb7575fba4501aff4932c2cc952bf9f)

[FIX] load_data: update to version 17.0

---

openupgradelib/openupgrade_160.py
openupgradelib/openupgrade_tools.py

Avoid record values which html is empty using the same rules that odoo.tools.is_html_empty uses. This way we can simplify the call avoiding a default domain as well. In any case, we can use that domain to refine certain models.
cc @Tecnativa TT46020
please check @pedrobaeza

[IMP] BS4->BS5: performance

---

openupgradelib/openupgrade_160.py
openupgradelib/openupgrade_tools.py

The improvement made in 40741d960477bfcfea5c1e6a518863a7e6f92065 couldn't deal with json columns of translatable fields.
In any case a more simpler approach can be took if we simply discard all the records which don't even have a `class` attribute in their html code, meaning that we don't need to make the Bootstrap migration at all.
cc @Tecnativa TT46020

[FIX][IMP] _convert_field_bootstrap_4to5_orm: translatable fields

---

openupgradelib/openupgrade.py

To have a hint on possible bottleneck issues for filters with heavy queries. We can disable it setting the new `verbose` parameter to `False`.
cc @Tecnativa TT46020
check @pedrobaeza

[IMP] disable_invalid_filters: log filter probes

---

openupgradelib/openupgrade_160.py

We're making use of core's `_get_translation_upgrade_queries` which aside from provide the proper queries to upgrade the translated fields to the new json structure tries to cleanup the former ir_tanslation records.
In OpenUpgrade we try to keep historic info after migration so we're able to quickly react to possible inconsistencies.
cc @Tecnativa TT49615

[FIX] migrate_translations_to_jsonb: avoid ir_translation terms cleanup

---

openupgradelib/openupgrade_160.py

Follow-up to
-  #374 
and related with
-  https://github.com/OCA/OpenUpgrade/pull/4477
Odoo's core method doesn't convert columns to jsonb. We need to make sure is done befor migrating the translations.
cc @Tecnativa TT49615

[FIX] migrate_translations_to_jsonb: convert columns to jsonb

---

openupgradelib/openupgrade_merge_records.py

The passed value is a recordset, so we should assign the ID of it.
Solves OCA/OpenUpgrade#4419
@Tecnativa

[FIX] openupgrade_merge_records: Adjust m2o value with ORM

---

openupgradelib/openupgrade_160.py

We can't log each translation query, as they are a lot (one per record of each of the translatable columns for all the models), and there are columns like ir_ui_view~arch_db that are very long.
@Tecnativa

[FIX] migrate_translations_to_jsonb: Less verbose

---

openupgradelib/openupgrade.py

Without this patch, if you call this function with a filename that can't be found, you'll get a confusing error like `NameError: name 'fp' is not defined`, that gives no details about the real problem.
@moduon MT-7047

[FIX] load_data: fail early on missing path

---

openupgradelib/openupgrade.py

Improve convert_field_to_html method: added translate=False parameter to handle translatable fields

[IMP]convert_field_to_html: manage translated fields

---

openupgradelib/openupgrade.py

Fixes https://github.com/OCA/openupgradelib/pull/384. Always consider some people still are working on python3.5 🤷🏻‍♂️

[FIX] convert_field_to_html: f-string compatibility

---

openupgradelib/openupgrade.py

`odoo.tools.ustr` is deprecated since Odoo 18. See full comment here: https://github.com/odoo/odoo/blob/e65d31339d383169bfebab7619073d7117198cfa/odoo/loglevels.py#L65
This improvement avoids raising the warning in the logs.

[FIX] logged_query: deprecation warning for tools.ustr for version >= 18

---

openupgradelib/openupgrade.py

it's not true for some versions of OpenUpgrade already that we need to retain the column's value manually, because we centrally [patch away dropping columns](https://github.com/OCA/OpenUpgrade/blob/14.0/openupgrade_framework/odoo_patch/odoo/addons/base/models/ir_model.py#L34).
The recommendation leads to [confusion](https://github.com/OCA/OpenUpgrade/pull/4465#discussion_r1806480453), so I suggest to restrict it to ancient versions of OpenUpgrade.

[UPD] m2o_to_x2m: docstring recommends outdated usage

---

openupgradelib/openupgrade.py

After a migration it was not possible to open the settings submenu: "User-defined filters".
This was due to invalid user filters.
The current script is not testing action_id. Some user filters contained deleted `ir.actions.actions`.
It was then failing when performing the `web_read`.
In this PR I'm adding a test related to the inhexistance of the related `ir.actions.actions`.

[IMP]openupgrade: disable_invalid_filters

---

openupgradelib/openupgrade.py

We found the following error when trying to upload csv files via the load_data method:
```
Traceback (most recent call last):
File "/home/odoo/src/openupgradelib/openupgradelib/openupgrade.py", line 2304, in wrapped_function
func(
File "/home/odoo/src/repositories/ingadhoc-odoo-saas-adhoc/saas_client_l10n_ar/migrations/16.0.1.9.0/post-migration.py", line 12, in migrate
openupgrade.load_data(env.cr, 'l10n_ar', 'data/res.country.csv')
File "/home/odoo/src/openupgradelib/openupgradelib/openupgrade.py", line 353, in load_data
tools.convert_csv_import(
File "/home/odoo/src/odoo/odoo/tools/convert.py", line 780, in convert_csv_import
reader = pycompat.csv_reader(io.BytesIO(csvcontent), quotechar='"', delimiter=',')
TypeError: a bytes-like object is required, not 'str'
2024-12-13 17:27:20,327 75 …
```

[FIX] load_data: switch to binary mode for recent versions

---

openupgradelib/openupgrade.py

model `ir.property` was removed in commit https://github.com/odoo/odoo/commit/de302c2 in version `18.0` so if new databases is initialized from 18.0 onwards will not have `ir_property` table then there will be an error exception that `relation ir_property does not exist` when using the `rename_models` function

[IMP] rename_models: add condition to check version and existence of ir_property table

---

openupgradelib/openupgrade.py

The names in ir_model_data use the model converted name instead of table name.

[FIX] rename_models: don't call get_model2table

---

openupgradelib/openupgrade.py

Fix the error indicated in https://github.com/OCA/l10n-spain/issues/4092 after https://github.com/odoo/odoo/pull/202014 merge, and potentially close the issue #409

[FIX] openupgrade: fix module name retrieval

---

openupgradelib/openupgrade.py

Before using `get_model2table` in `add_column` (see https://github.com/OCA/openupgradelib/pull/412), I realized one thing: We need to track versions in `get_model2table`. Because `mail.notification` has its own table since v15.

[FIX] get_model2table: fill and track versions

---

openupgradelib/openupgrade.py

Sometimes, you only want to precreate the column, not the `ir.model.fields` entry, `ir.model.data` entry, etc. In fact, since v12, `add_fields` is less needed as Odoo always add the XML-ID entry, so you may be interested only in the SQL column.

[ADD] add_column: split from add_fields

---

openupgradelib/openupgrade.py

Boolean fields may want to have False as initialization value (instead of null), so we should allow it.

[IMP] add_columns: Allow False as initialization value

---

openupgradelib/openupgrade_merge_records.py

See https://github.com/odoo-dev/odoo/commit/4b1c9a89529bea56d4837e0065070d8463f46258.

[FIX] merge_records: norecompute was deprecated in v17

---

openupgradelib/openupgrade.py

This way, we keep the compatibility with existing calls to add_fields using False as "filling value" in specifications of non boolean fields.
Fixes #416
@Tecnativa

[FIX] add_columns: Don't consider False for non boolean columns

---

openupgradelib/openupgrade.py

It seems it was forgotten in https://github.com/OCA/openupgradelib/pull/418.

[FIX] add_columns: remove default False for boolean field
